version: '3.8'

services:
  # Tuna Security Scanner (Docker Hub'dan)
  web:
    image: mustafatunahantuna/tuna_zap:latest
    container_name: tuna_security_scanner
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - DATABASE_URL=sqlite:///app.db
    volumes:
      - ./data:/app/data
      - ./reports:/app/zap-reports
    depends_on:
      - zap
    restart: unless-stopped

  # OWASP ZAP Scanner
  zap:
    image: zaproxy/zap-stable:latest
    container_name: tuna_zap_scanner
    user: root
    ports:
      - "8080:8080"
    volumes:
      - ./reports:/zap/wrk
    command: >
      zap.sh -daemon 
      -host 0.0.0.0 
      -port 8080 
      -config api.addrs.addr.name=.* 
      -config api.addrs.addr.regex=true 
      -config api.disablekey=true
    restart: unless-stopped 