version: '3.8'

services:
  # Ana Uygulama (Basit SQLite)
  web:
    image: mustafatunahantuna/tuna_zap:latest
    container_name: security_app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      SECRET_KEY: simple-secret-key
    volumes:
      - app_data:/app/instance

  # ZAP Tarayıcı
  zap:
    image: zaproxy/zap-stable
    container_name: zap_scanner
    ports:
      - "8080:8080"
    volumes:
      - zap_reports:/zap/wrk
    command: >
      zap.sh -daemon -host 0.0.0.0 -port 8080 
      -config api.disablekey=true
      -config api.incerrordetails=true
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
    restart: unless-stopped

volumes:
  app_data: 
  zap_reports: