"""Initial migration: create scan and vulnerability tables

Revision ID: 46a68aedac7c
Revises: 
Create Date: 2025-07-24 22:34:57.159759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a68aedac7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_url'), ['url'], unique=False)

    op.create_table('vulnerability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.String(length=64), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerability')
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_url'))

    op.drop_table('scan')
    # ### end Alembic commands ###
